CREATE TABLE paises(id int(11) AUTO_INCREMENT, nombre VARCHAR(255), fifa VARCHAR(3), iso VARCHAR(2), PRIMARY KEY(id));
INSERT INTO paises(nombre,fifa,iso) VALUES('Alemania','ger','de')
, ('Argelia','alg','dz')
, ('Argentina','arg','ar')
, ('Australia','aus','au')
, ('Belgica','bel','be')
, ('Bosnia y Herzegovina','bih','ba')
, ('Brasil','bra','br')
, ('Camerun','cmr','cm')
, ('Chile','chi','cl')
, ('Colombia','col','co')
, ('Corea del sur','kor','kr')
, ('Costa de marfil','civ','ci')
, ('Costa rica','crc','cr')
, ('Croacia','cro','hr')
, ('Ecuador','ecu','ec')
, ('España','esp','es')
, ('Estados Unidos','usa','us')
, ('Francia','fra','fr')
, ('Ghana','gha','gh')
, ('Grecia','gre','gr')
, ('Holanda','ned','nl')
, ('Honduras','hon','hn')
, ('Inglaterra','eng','en')
, ('Iran','irn','ir')
, ('Italia','ita','it')
, ('Japon','jpn','jp')
, ('Mexico','mex','mx')
, ('Nigeria','nga','ng')
, ('Portugal','por','pt')
, ('Rusia','rus','ru')
, ('Suiza','sui','ch')
, ('Uruguay','uru','uy');